### ISSUE TITLE
automatic scans

### ISSUE THREAD

**Issue by Volarn** [GDATASoftwareAG/nextcloud-gdata-antivirus#118]
Hello there,

I'm having problems with the function of the app. The integration seems to have worked.

I have created an account with GData and saved it in the settings.

Manual scanning for viruses works perfectly. But the automatic scanning on upload, or the automatic scanning in general, does not work. 

Here is a screenshot:

![image](https://github.com/user-attachments/assets/d553d704-d8f4-4644-8390-ae3edac31a10)

What am I doing wrong here?

Greetings,
Volker Arndt

**Comment by Volarn** [comment]
Hello,

I have checked again. It seems that it only affects folders created with the Group Folder app.

How can I make sure that these folders are also scanned?


Greetings,
Volker Arndt

**Comment by GermanCoding** [comment]
Can you confirm that this is the app you're referring to? https://apps.nextcloud.com/apps/groupfolders

**Comment by Volarn** [comment]
Hello,

yes this is the app.

**Comment by unglaublicherdude** [comment]
We can confirm the issue as we just tested the constellation. We will have a look on that.

**Comment by unglaublicherdude** [comment]
We just released the Versions [28.4.0](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/releases/tag/28.4.0)  and [29.4.1](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/releases/tag/29.4.1) with the Bugfix for this issue.
