### ISSUE TITLE
Scan files on creation

### ISSUE THREAD

**Issue by lennartdohmann** [GDATASoftwareAG/nextcloud-gdata-antivirus#85]
## Steps to reproduce
1. Run any Nextcloud instance
2. Install, enable and set up G DATA Antivirus App
3. Create a any file within the Nextcloud UI
4. Should be scanned on creation

## Expected
Files should be scanned after they have been created to prevent malicious content from being created in Nextcloud itself and bypassing the on-upload scan function.

## Actual
Files are not scanned by creating them, however they would eventually be captured by automatic scanning, but this can take time. Affects all app versions.

**Comment by doxthree** [comment]
fyi: this feature is standard installes by nextcloud and maintained by this app here
https://github.com/nextcloud/text
