### ISSUE TITLE
BUG: Unscanned tag is added even though it is disabled

### ISSUE THREAD

**Issue by olive-spore-734** [GDATASoftwareAG/nextcloud-gdata-antivirus#95]
I installed the app and changed nothing except turning on "Disable Unscanned tag". Username, Password (etc.) are still empty aswell.
But every file is being tagged with "unscanned" - i tried to deactivate the app but it seems to have set up a background job and just keeps going. I think my app is haunted. **Spooky.**

**Comment by lennartdohmann** [comment]
Thank you @olive-spore-734 for reporting this issue. To help us investigate and reproduce the problem, could you please provide the following information: 

- Nextcloud Version: The version of Nextcloud you are using.
- App Version: The version of the Nextcloud Antivirus app you have installed.

If it is possible, it would also be very nice to provide as much as you can of the following information:
- PHP Version: The version of PHP running on your server.
- Database: The type and version of the database you are using (e.g., MySQL, PostgreSQL).
- Web Server: The type and version of the web server you are using (e.g., Apache, Nginx). Or do you use the “fpm” tag?
- Logs: Any relevant logs from Nextcloud or your web server that might help us understand the issue.

Additionally, please let us know if you have tried any troubleshooting steps so far, such as clearing the cache, restarting the web server, or re-enabling the app.

**Comment by olive-spore-734** [comment]
Thanks for responding!
I did the following:
- deactivated the app and deleted the configs
- deactivated the automated tags app
- deactivated the tags app
- stopped the cron job responsible for tagging "unscanned", but just by the jobs ID, so that probably didnt do much
- checked the activity and logs
- reactivated the tags app, it kept going
It kept tagging for about 10 hours after trying to stop it by doing the above - then it stopped and deleted the tag.
So it seems it solved itself after half a day (at most)  

Sorry for not providing the information you asked for from the start:
- Nextcloud Version: 29.0.4
- App Version: 29.2.1
- PHP: 8.2.20
- Database: MySQL 10.11.6
- Web Server: (This i couldnt figure out)
- Logs: I was looking at the logs on debug level, but did not spot anything related to this.
